//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public Nullable<int> departamento { get; set; }
        public Nullable<int> cargo { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public Nullable<double> salario { get; set; }
        public Nullable<bool> estatus { get; set; }
    
        public virtual cargo cargo1 { get; set; }
        public virtual departamento departamento1 { get; set; }
    }
}
