//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HubHumano.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hubhumanoEntities1 : DbContext
    {
        public hubhumanoEntities1()
            : base("name=hubhumanoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargo> cargoes { get; set; }
        public virtual DbSet<departamento> departamentoes { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
    }
}
